require("__SpaceModFeorasFork__/prototypes/technology")
require("__SpaceModFeorasFork__/prototypes/style")
require("__SpaceModFeorasFork__/prototypes/item")
require("__SpaceModFeorasFork__/prototypes/recipe")
require("__SpaceModFeorasFork__/prototypes/entities")
